// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store_Web.Models;

#nullable disable

namespace Store_Web.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240919204000_ProductSeedData")]
    partial class ProductSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Store_Web.Models.Product", b =>
                {
                    b.Property<int>("Product_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Product_Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Product_Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Product_Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Product_Id = 1,
                            Product_Name = "Computer",
                            Product_Price = 28000m
                        },
                        new
                        {
                            Product_Id = 2,
                            Product_Name = "Monitor",
                            Product_Price = 8000m
                        },
                        new
                        {
                            Product_Id = 3,
                            Product_Name = "Mouse",
                            Product_Price = 3000m
                        },
                        new
                        {
                            Product_Id = 4,
                            Product_Name = "Keyboard",
                            Product_Price = 4000m
                        },
                        new
                        {
                            Product_Id = 5,
                            Product_Name = "MousePad",
                            Product_Price = 200m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
